export const TYPES = {
    GET_DATA: "GET_DATA",
    CREATE_DATA: "CREATE_DATA",
    EDIT_DATA: "EDIT_DATA",
    LOADING_DATA: "LOADING_DATA",
    SET_ERROR: "SET_ERROR",
    HANDLE_CHANGE: "HANDLE_CHANGE",
    HANDLE_RESET: "HANDLE_RESET",
    HANDLE_EDIT: "HANDLE_EDIT"
};